### ISSUE TITLE
Next steps for OmniLedger

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#211]
Here is a summary of the proposed next steps for OmniLedger for Linus:
- [ ] Phonebook: #213
- [ ] GDPR data handling: #214
- [ ] Add Genesis-header to proof: dedis/cothority#2347
- [ ] Check ClientTransactions: dedis/cothority#2205
- [ ] OmniLedger Explorer: #216
- [ ] Extend DARCs: dedis/cothority#2186
- [ ] Add rewards: dedis/cothority#2188
- [ ] Proof-of-Personhood: dedis/cothority#2189
- [ ] Bug fixing
  - [ ] dedis/cothority#2080
  - [ ] dedis/onet#617

ETA: 1month -> x2, unit change -> 2 years

Done:
- [x] Dynacred 2: #212 
- [x] Enable observability: dedis/onet#618
- [x] Lock down nodes: dedis/cothority#2204
- [x] Link BEVM with ByzCoin: dedis/cothority#2187
- [x] Merge the rollup-protocol from the students' project at dedis/cothority#2321

**Comment by ineiti** [comment]
Sundown
