### ISSUE TITLE
Personhood at OpenHouse

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#69]
For the OpenHouse demo, the personhood app needs some changes:
- [x] Remove non-alias attributes #106
- [x] Test, test, test #83 #84 #85 #86
  - [x] Multi-organizer doesn't work with Adri
  - [x] Change link in app to oh19.c4dt.org
- [x] Challenge #94 
  - [x] Sign up for the challenge (currently automatic sign-up)
  - [x] Limit challenge to 1 day #106
  - [x] Make board of winners
- [x] Admin authorizations: #103
  - [x] Only admins can create parties
  - [x] Admins can wipe RPS games
- [x] Finish French translation #96 
- [x] RPS improvements
  - [x] locking of game if somebody joins #102
  - [x] auto-loose if the game is not revealed in time #97 #101
- [x] Personhood-delete only for admins (through darc) #93 
- [x] Use Polls on all parties #95 
- [x] home/send_coin -> invite
- [x] Remove meetups from main screen and from challenge
- [x] Fix bugs from first small party #89 #90
- [x] Deploy apps
  - [x] Android store #82 
  - [x] iOS applivery
- [x] Add references #79 
- [x] Update the personhood-score to include - #79
  - [x] Polls
  - [x] Rock-Paper-Scissors
  - [x] References
- [x] Translate into French #80

**Comment by ineiti** [comment]
Done - nice gatherings!
